
name: Run Tests
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Zig
      run: |
        sudo apt-get update
        sudo apt-get install -y xz-utils
        wget https://ziglang.org/download/0.14.0/zig-linux-x86_64-0.14.0.tar.xz
        tar -xf zig-linux-x86_64-0.14.0.tar.xz
        echo "$PWD/zig-linux-x86_64-0.14.0" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-all-dev libpcre2-dev libcli11-dev catch2
    - name: Run tests
      env:
        DEFAULT_LIB_PATH: /usr/lib/x86_64-linux-gnu
        DEFAULT_INCLUDE_PATH: /usr/include
      run: zig build test
